name: my-test-action
description: test GitHub Action.
author: Long0x0

branding:
  icon: mail
  color: blue

inputs:
  account:
    description: account.
    required: true
  password:
    description: password.
    required: true
  token:
    description: token.
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Test python
      env:
        INPUT_ACCOUNT: ${{ inputs.account }}
        INPUT_PASSWORD: ${{ inputs.password }}
        INPUT_TOKEN: ${{ inputs.token }}
      run: |
        pip install -r ${{ github.action_path }}/src/requirements.txt
        python ${{ github.action_path }}/src/test.py
      shell: bash
